### ISSUE TITLE
Volume Mapping?

### ISSUE THREAD

**Issue by LeeThompson** [youtous/rainloop#1]
Is there a volume map option to save Rainloop configuration data outside of the container?

**Comment by youtous** [comment]
Hi,
You can map the following file `/rainloop/data/_data_/_default_/configs/application.ini` or the whole directory: `/rainloop/data/_data_/_default_/configs/`. 

_docker-compose.yml_
```
services:

  rainloop:
    image: youtous/rainloop:latest
    container_name: rainloop
    ports:
      - "80:8888"
    volumes:
      - ./data:/rainloop/data
      - ./config:/rainloop/data/_data_/_default_/configs/
```
